### ISSUE TITLE
Which version of CMUDict is used?

### ISSUE THREAD

**Issue by rbracco** [prosegrinder/python-cmudict#19]
Hi, I am using [pronouncing](https://pypi.org/project/pronouncing/) which wraps python-cmudict. I found that the transcription of "African" yields ['AE1 F R AH0 K AH0 N', 'AE1 F R IH0 K AH0 N'], but the [version on CMU's Website (0.7b)](http://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict/cmudict-0.7b) lists only 'AE1 F R IH0 K AH0 N'. 

Which version of CMUDict is being used by python-cmudict and where is it maintained?

Thank you.

**Comment by hugovk** [comment]
The [releases page](https://github.com/prosegrinder/python-cmudict/releases) shows the date cmudict was updated, for example:

> v0.4.5
> Updated cmudict as of 2020-10-01.


And the [README](https://github.com/prosegrinder/python-cmudict) says:

> CMUdict is a versioned python wrapper package for [The CMU Pronouncing Dictionary](https://github.com/cmusphinx/cmudict) data files.

Which links to:

* https://github.com/cmusphinx/cmudict

That repo is updated more often than the version on CMU's website.

**Comment by rbracco** [comment]
Great, thanks so much for the clarification!
