### ISSUE TITLE
Going out on a limb here, but I assume "cumdict" is a typo in the readme.

### ISSUE THREAD

**Issue by JoelDesante** [prosegrinder/python-cmudict#23]
For the less mature individuals out there (like me), the appearance of the typo in the following excerpt makes me giggle.

> Three additional functions are included to maintain compatibility with NLTK: **cumdict**.entries(), cmudict.raw(), and cmudict.words(). See the nltk.corpus.reader.cmudict documentation for details:
**- README.md**

I've made this issue so that I may make a pull request to resolve this typo.

**Comment by JoelDesante** [comment]
My bad, still new to this ^^^

**Comment by davidlday** [comment]
Yeah. No. Total typo. Gave me a much needed giggle today, too. Thanks for the contribution!
